apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
# FIXME: failed to set memlock rlimit: operation not permitted
# unable to set memory resource limits
# patches:
#   - patch: |
#       - op: replace
#         path: /metadata/labels/pod-security.kubernetes.io~1enforce
#         value: privileged
#     target:
#       kind: Namespace
#       name: kube-system
