---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: cilium
      version: "1.18.0" # {"$imagepolicy": "cilium:cilium:tag"}
      sourceRef:
        kind: HelmRepository
        name: cilium
  releaseName: cilium
  values:
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    externalIPs:
      enabled: true

    hostFirewall:
      enabled: true
    policyAuditMode: false

    hostPort:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true
        # prometheus:
        #   enabled: true
        #   serviceMonitor:
        #     enabled: true
        # FIXME: hubble-relay out of memory
        resources: {}
        tls:
          server:
            enabled: true
      peerService:
        targetPort: 4244
        clusterDomain: cluster.local # ${CLUSTER_DOMAIN}
      tls:
        enabled: true
        auto:
          enabled: true
          method: certmanager
          certManagerIssuerRef:
            group: cert-manager.io
            kind: ClusterIssuer
            name: ca-issuer
      ui:
        enabled: true

    k8sNetworkPolicy:
      enabled: true

    k8sServiceHost: localhost
    k8sServicePort: 7445

    nodePort:
      enabled: true

    operator:
      # Single node port
      replicas: 1

    # prometheus:
    #   metricsService: true
    #   enabled: true
    #   # port: 9962
    #   serviceMonitor:
    #     enabled: true
    #     trustCRDsExist: true
