---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled
resources:
  - podmonitor.yaml
  - servicemonitor.yaml
  - rbac.yaml
# FIXME: DS_PROMETHEUS variable not set
# configMapGenerator:
#   - name: flux-grafana-dashboards
#     files:
#       - dashboards/control-plane.json
#       - dashboards/cluster.json
#     options:
#       labels:
#         grafana_dashboard: "1"
#         app.kubernetes.io/part-of: flux
#         app.kubernetes.io/component: monitoring
