# Permissions for Flux tenants to own Prometheus Operator resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: kube-prometheus-stack-admin-role
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors/status
      - servicemonitors/status
    verbs:
      - get
