---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-operator-chart # controlplaneio-fluxcd
  releaseName: flux-operator
  # https://github.com/controlplaneio-fluxcd/charts/blob/main/charts/flux-operator/values.yaml
  values:
    multitenancy:
      enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    # tolerations:
    #   - key: node.kubernetes.io/network-unavailable
