---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
spec:
  interval: 1h
  # timeout: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: "0.73.3" # {"$imagepolicy": "gitlab-runner:gitlab-runner:tag"}
      sourceRef:
        kind: HelmRepository
        name: gitlab
  releaseName: gitlab-runner
  # https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/main/values.yaml
  values:
    concurrent: 4
    gitlabUrl: https://gitlab.com
    # secret: gitlab-runner # <release>-gitlab-runner-secret
    rbac:
      create: true
      # https://docs.gitlab.com/runner/executors/kubernetes/index.html#configure-runner-api-permissions
      rules:
        - resources: ["events"]
          verbs: ["list", "watch"]
        - resources: ["namespaces"]
          verbs: ["create", "delete"]
        - resources: ["pods"]
          verbs: ["create", "delete", "get"]
        - apiGroups: [""]
          resources: ["pods/attach", "pods/exec"]
          verbs: ["get", "create", "patch", "delete"]
        - apiGroups: [""]
          resources: ["pods/log"]
          verbs: ["get", "list"]
        - resources: ["secrets"]
          verbs: ["create", "delete", "get", "update"]
        - resources: ["serviceaccounts"]
          verbs: ["get"]
        - resources: ["services"]
          verbs: ["create", "get"]
        # - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        #   resources: ["kustomizations"]
        #   verbs: ["get"]
        - apiGroups: ["source.toolkit.fluxcd.io"]
          resources: ["ocirepositories"]
          verbs: ["get"]
      clusterWideAccess: false
    serviceAccount:
      create: true
      # name: ""

    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    # service:
    #   enabled: true

    replicas: 1
    runners:
      # runner configuration, where the multi line string is evaluated as a
      # template so you can specify helm values inside of it.
      #
      # tpl: https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
      # runner configuration: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "alpine"
            # https://docs.gitlab.com/runner/executors/kubernetes/#set-a-pull-policy
            # pull_policy = ["never", "if-not-present", "always", "always"]
            pull_policy = ["if-not-present", "always", "always"]
      ## Absolute path for an existing runner configuration file
      ## Can be used alongside "volumes" and "volumeMounts" to use an external config file
      ## Active if runners.config is empty or null
      # configPath: ""
      # executor: kubernetes
    extraObjects: []
    # - apiVersion: external-secrets.io/v1
    #   kind: ExternalSecret
    #   metadata:
    #     name: '{{ include "gitlab-runner.secret" . }}'
    #   spec:
    #     refreshInterval: 1h
    #     secretStoreRef:
    #       kind: SecretStore
    #       name: my-secret-store
    #     target:
    #       template:
    #         data:
    #           runner-registration-token: "" # need to leave as an empty string for compatibility reasons
    #           runner-token: "{{`{{ .runnerToken }}`}}"
    #     dataFrom:
    #     - extract:
    #         key: my-secret-store-secret
    secrets:
      - name: gitlab-runner
    # - name: myOtherSecret
    #   items:
    #     - key: key_one
    #       path: path_one

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      privileged: false
      capabilities:
        drop: ["ALL"]
