apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-operator
resources:
  - repository.yaml
  - release.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: tailscale
