---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  releaseName: external-secrets
  values:
    bitwarden-sdk-server:
      enabled: true

    installCRDs: true

    # processClusterExternalSecret: false
    # processClusterStore: false
    # processPushSecret: false

    # crds:
    #   createClusterExternalSecret: false
    #   createClusterSecretStore: false
    #   createPushSecret: false

    # # If set to true, create scoped RBAC roles under the scoped namespace
    # # and implicitly disable cluster stores and cluster external secrets
    # scopedRBAC: true

    # # Specify the namespace where external secrets should be reconciled
    # scopedNamespace: external-secrets

    # webhook:
    #   certManager:
    #     enabled: true
    #     addInjectorAnnotations: true
    #     cert:
    #       create: true
    #       issuerRef:
    #         group: cert-manager.io
    #         kind: ClusterIssuer
    #         name: selfsigned-issuer
    #       duration: "8760h" # Default: 1 year
    #       revisionHistoryLimit: 0
    #       renewBefore: ""
    #       annotations: {}

    certController:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
    # dnsPolicy: ClusterFirst
    # dnsConfig: {}
    # podSpecExtra: {}
