apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin # grafana-secrets-{{ .Release.Name }}
spec:
  secretStoreRef:
    name: admin-user
    kind: SecretStore
  refreshInterval: 0s # 1h
  target:
    name: grafana-admin
    template:
      engineVersion: v2
      data:
        user: "{{ .user }}"
        password: "{{ .password }}"
        credentials: |
          {
            "url": "http://kube-prometheus-stack-grafana.monitoring",
            "auth": "{{ .user }}:{{ .password }}"
          }
  data:
    - remoteRef:
        key: user
      secretKey: user
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-42
