apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: metrics-server
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/metrics-server
  ref:
    tag: "3.12.2" # {"$imagepolicy": "infra:metrics-server:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  serviceAccountName: flux
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: metrics-server
  # https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
  values:
    args:
      - --kubelet-insecure-tls
