apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: metrics-server
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/metrics-server
  ref:
    tag: "7.4.1" # {"$imagepolicy": "infra:metrics-server:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  serviceAccountName: flux
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: metrics-server
  # https://artifacthub.io/packages/helm/bitnami/metrics-server
  values:
    global:
      imageRegistry: public.ecr.aws
      security:
        allowInsecureImages: true
    extraArgs:
      - --kubelet-insecure-tls
