---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager-chart
  releaseName: cert-manager
  # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/cert-manager/refs/heads/master/deploy/charts/cert-manager/values.schema.json
    crds:
      enabled: true
      keep: false
    webhook:
      hostNetwork: true
      networkPolicy:
        enabled: true
    # https://cert-manager.io/docs/usage/gateway/
    # config:
    #   apiVersion: controller.config.cert-manager.io/v1alpha1
    #   kind: ControllerConfiguration
    #   enableGatewayAPI: true
    # https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
    tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
