---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  releaseName: cert-manager
  chartRef:
    kind: OCIRepository
    name: cert-manager-chart
  values:
    installCRDs: true
