apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |
      - op: replace
        path: /spec/values/policyAuditMode
        value: true
    target:
      kind: HelmRelease
      name: cilium
